# Setup
title:            Nan
tagline:          'NUS|Gatech|Wego|AILab'
description:      'I love data stuff. Made by <a href="https://twitter.com/xia0nan" target="_blank">@xia0nan</a>'
url:              https://nanx.cc/
baseurl:          'https://nanx.cc/'
paginate:         5

# About and contact
author:
  name:           'Xiao Nan'
  url:            https://twitter.com/xia0nan/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/xia0nan/

linkedin:         https://www.linkedin.com/in/xiao-nan/