# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nan
tagline:          'NUS & Wego'
description:      'I love data stuff'
url:              http://xnone.github.io
baseurl:          ''

author:
  name:           'Xiao Nan'
  url:            https://twitter.com/xnone90

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/xnone/
