# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nan
tagline:          'NUS & Wego'
description:      'I love data stuff'
url:              https://nanx.cc/
baseurl:          'https://nanx.cc/'

author:
  name:           'Xiao Nan'
  url:            https://twitter.com/xia0nan/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/xia0nan/