# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nan
tagline:          'NUS & Wego'
description:      'I love data stuff'
url:              https://nanx.cc/
baseurl:          ''

author:
  name:           'Xiao Nan'
  url:            https://twitter.com/xia0nan/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/xia0nan/

theme: jekyll-theme-minimal