# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nan
tagline:          'NUS & Wego'
description:      'I love data stuff. Made by <a href="https://twitter.com/xia0nan" target="_blank">@xia0nan</a>'
url:              https://nanx.cc/
baseurl:          'https://nanx.cc/'

author:
  name:           'Xiao Nan'
  url:            https://twitter.com/xia0nan/

paginate:         5

# Custom vars
version:          0.9.0

github:
  repo:           https://github.com/xia0nan/

linkedin:         https://www.linkedin.com/in/xiao-nan/